repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-toml
    - id: debug-statements

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    types: [python]
    exclude: setup.py

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: poetry run pytest --exitfirst
    types: [python]

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: poetry run pytest --cov --cov-fail-under=100
    types: [python]
    pass_filenames: false
